#!/bin/bash

DEFAULT_LOCAL_A=${NMF_HOME}/Data/A
DEFAULT_LOCAL_H=${NMF_HOME}/Data/H
DEFAULT_LOCAL_W=${NMF_HOME}/Data/W
DEFAULT_REMOTE_A=AOriginal
DEFAULT_REMOTE_H=HOriginal
DEFAULT_REMOTE_W=WOriginal
DEFAULT_REMOTE_INITIAL_W=W0
DEFAULT_REMOTE_INITIAL_H=H0
DEFAULT_REMOTE_INITIAL_A=A0

DEFAULT_JAR=${NMF_HOME}/dist/FinalProject.jar


K_DIM=2

${NMF_HOME}/Script/LoadData.sh ${DEFAULT_LOCAL_A} ${DEFAULT_REMOTE_A} ${DEFAULT_LOCAL_H} ${DEFAULT_REMOTE_H} ${DEFAULT_LOCAL_W} ${DEFAULT_REMOTE_W}

${HADOOP_HOME}/bin/hadoop jar ${DEFAULT_JAR} ExternalPhase.TextToGSequenceMatrixWHTranslator ${DEFAULT_REMOTE_W} ${DEFAULT_REMOTE_INITIAL_W} ${K_DIM} 16
${HADOOP_HOME}/bin/hadoop jar ${DEFAULT_JAR} ExternalPhase.TextToGSequenceMatrixWHTranslator ${DEFAULT_REMOTE_H} ${DEFAULT_REMOTE_INITIAL_H} ${K_DIM} 16
${HADOOP_HOME}/bin/hadoop jar ${DEFAULT_JAR} ExternalPhase.TextToGSequenceSparseElementTranslator ${DEFAULT_REMOTE_A} ${DEFAULT_REMOTE_INITIAL_A} 46
